### ISSUE TITLE
Add iETarget Mixin

### ISSUE THREAD

**Issue by mike3run** [mike3run/manila-mixins#2]
```scss
@mixin std-background {
  background-position: center;
  background-size: cover;
  background-repeat: no-repeat;
}
```
