### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by mike3run** [mike3run/manila-mixins#4]
```scss
@mixin debug {
  @at-root {
    * {
      outline: 1px solid red;
    }
  }
}
```
