### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by shelldandy** [mike3run/manila-mixins#7]
Buttons are stupid here's a solution:

```scss
@mixin reset-btn {
  appearance: none;
  border: none;
  border-radius: 0;
  background: none;
  margin: 0;
  padding: 0;
  font: inherit;
  line-height: inherit;
}
```
